### ISSUE TITLE
Programmatically set the title for pdf file opening in new tab (_blank) in browser

### ISSUE THREAD

**Issue by anaashrafi** [hashirshoaeb/home#27]
When you click on the resume button in the about me section, it opens a new tab with the resume but the tab name does not match the name of the resume file.

**Comment by hashirshoaeb** [comment]
<img width="562" alt="Screenshot 2020-07-14 at 3 01 38 AM" src="https://user-images.githubusercontent.com/35165481/87358414-38a3d180-c57f-11ea-80b0-41fc77cb2387.png">

**Query**: How to programmatically set the title for pdf file opening in new tab (_blank) in browser. As screenshot attached above.
**Possible solution:** https://stackoverflow.com/questions/50759857/how-to-set-title-for-pdf-file-opening-in-new-tab-blank-in-browser 
But it's not the best solution so far.

**Comment by hashirshoaeb** [comment]
If anyone can solve this issue. Please feel free to send Pull Request. 

Happy coding

**Comment by TowerX** [comment]
@anaashrafi , @hashirshoaeb, I stumbled upon this issue and found it very interesting. I inspected the actual PDF trying to find a possible solution to this and here it shows where it is getting the **<title>** from:

![resumeTittleIssue](https://user-images.githubusercontent.com/8185609/91116383-3b9fe080-e65a-11ea-8905-9e4785b9a94e.PNG)

Probably out of scope for this **Issue** but here it goes: I think you can edit the PDF before uploading it to the website so it displays the actual Title you need. The <title> tag is been generated by the PDF Title field and not the Filename. 

Let me know what you think.

**Comment by hashirshoaeb** [comment]
Damn How can I be so dumb. Thanks a lot @TowerX for figuring out the root of this issue. 
So it means is that instead of setting(overwriting) the title of the browser tab. I need to set(overwrite) the Title(metadata) of pdf file. This will automatically update the browser title. 

Following are the possible solutions that found after a bit of googling:
- Manual way: [How to Change the PDF Title that appears in a web browser (using free software)](https://www.youtube.com/watch?v=vJw77is-f50)
- Programmatic way: [npm package pdf-lib](https://www.npmjs.com/package/pdf-lib#read-document-metadata)

I tried the **Manual way** and it worked. What do you suggest? Should I implement the **Programmatic way** into my code? Personally, I am finding it unnecessary to do it. 

Best,
Hashir

**Comment by TowerX** [comment]
@hashirshoaeb I'm glad! For this specific scenario, I think it is safe to say that a resume document won't change every day. By making sure the file meta is correct, you will have a nice page title. I don't think you need to go as far as finding a programmatic way unless you want a challenge :) Let me know if you have any other questions. Happy to help :)

Regards,

TowerX

**Comment by hashirshoaeb** [comment]
A website that can help in changing the title other metadata of pdf file. https://pdfcandy.com/result/3ecab7710648.html
