### ISSUE TITLE
React Class-Based Component to React Hooks Migration

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/home#9]

**Comment by yonis9** [comment]
Hi, which components do you want to transform into functional components with hooks?

**Comment by hashirshoaeb** [comment]
Hi @yonis9 
Thank you for taking interest. I'm thinking of migrating all the components to hooks. This will make the codebase look more clean. I'll appreciate your thoughts on it. 

Best,
Hashir

**Comment by yonis9** [comment]
I don't think it's mandatory but we can do it. 
In addition, maybe I didn't fully understand, But I think you misusing the state in some components, for example in the AboutMe.jsx:

    this.state = {
      heading: "About me",
      aboutDev: Configs.aboutDev,
      instaProfilePic: '',
      showInsta: Configs.showInstaProfilePic,
      resumeURL: Pdf
    };
  }`

I think you can get rid of the "heading" in the state since it never gets changed and affects the component, unless you want to reuse this component for other purposes with the same logic.

If you need any help I will be happy to take part.

**Comment by hashirshoaeb** [comment]
Yes @yonis9. I did this on purpose. So that I did not have to go into the code the change the text. Simply i can change this from state.

**Comment by yonis9** [comment]
OK no problem. So I will convert it to use hooks tomorrow, is it fine?

**Comment by hashirshoaeb** [comment]
Yeah Sure.

**Comment by hashirshoaeb** [comment]
The purpose is to increase the readability of code. By:
 - removing unnecessary things, 
- changing components to hooks
- reengineering complex logic to simple.

And feel free to share your ideas.
